### ISSUE TITLE
Node deprecation warnings

### ISSUE THREAD

**Issue by jasonday** [tjscollins/axe-crawler#1] opened 2017-11-09 18:24 UTC
Running axecrawler with any configuration:

`(node:6820) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): TypeError: Cannot read property 'verbose' of undefined`

`(node:17132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by jasonday** [comment] 2017-11-09 18:31
debugging:
```

PS C:\Users\xxxxx> axe-crawler xxxxxx.com --depth 0 --verbose debug
DEBUG: Crawling with options:
 { depth: 0,
  check: undefined,
  output: 'reports',
  ignore: '.*',
  whitelist: '.*',
  random: false,
  viewPorts:
   [ { name: 'mobile', width: 360, height: 640 },
     { name: 'tablet_vertical', width: 768, height: 1024 },
     { name: 'tablet_horizontal', width: 1024, height: 768 },
     { name: 'desktop', width: 1440, height: 900 } ],
  verbose: 'debug',
  domain: 'xxxxxx.com',
  logger: N { verbose: 'debug' } }
INFO: Found 1 links within xxxxxx.com
DEBUG: Queue to be tested:  Set { 'http://xxxxxx.com' }
INFO: Based on options, testing 1 urls
DEBUG: Testing 4 views:
DEBUG:  mobile: 360x640
DEBUG:  tablet_vertical: 768x1024
DEBUG:  tablet_horizontal: 1024x768
DEBUG:  desktop: 1440x900
DEBUG: Test case:  { url: 'http://xxxxxx.com',
  viewPort: { name: 'mobile', width: 360, height: 640 } }
DEBUG: Test case:  { url: 'http://xxxxxx.com',
  viewPort: { name: 'tablet_vertical', width: 768, height: 1024 } }
DEBUG: Test case:  { url: 'http://xxxxxx.com',
  viewPort: { name: 'tablet_horizontal', width: 1024, height: 768 } }
DEBUG: Test case:  { url: 'http://xxxxxx.com',
  viewPort: { name: 'desktop', width: 1440, height: 900 } }
(node:15836) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): TypeError: Cannot read property 'verbose' of undefined
(node:15836) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jasonday** [comment] 2017-11-09 23:23
Further testing: receiving this error on multiple machines

**Comment by tjscollins** [comment] 2017-11-13 03:15
Looks like you're missing the chromedriver (have to install separately, not managed by NPM).  I was only able to reproduce the error when I renamed the chromedriver executable, and then I got the same error at the same point in the program flow.

Check that chromedriver is installed on your PATH and let me know.  If that's the problem I'll add it to the README.

[Installation instructions for ChromeDriver](https://sites.google.com/a/chromium.org/chromedriver/)

**Comment by jasonday** [comment] 2017-11-13 14:29
I have chromedriver installed and added to path.

To give additional context, I had other devs test (internally and externally) and all ran into the same issue.  One of the devs rolled back to the prior version before the ES6 logger changes and was able to get axe-crawler to work.

**Comment by tjscollins** [comment] 2017-11-14 04:04
That's really weird then.  The only way I managed to recreate your logging output is if chromedriver is not installed correctly (tried on Ubuntu, OS X, and even a c9 ubuntu instance, just to try a totally blank environment).  Based on the logging output the error should be occurring in the routine which calls WebDriver, probably in lines 100-106 of index.js (based on the debug statement from line 99 getting called, but line 109 not getting called, though async makes it a little more complex than that).

Are you using node v6.11 or higher?  That's the only other thing I can think of, if the Logger class introduced the error, then maybe my babel preset is targeting a feature your node version doesn't support?

I've published a new version (0.4.2) with improved error handling and logging in that routine.  Since I 
 can't recreate the error, can you try it out and let me know what the error says?  It should catch and log the actual error now instead of just logging an unhandled promise rejection.

**Comment by AgnieszkaBorucka** [comment] 2017-11-14 12:54
I had the same issue when I wanted to test it yesterday, now it's

> DeprecationWarning: Calling an asynchronous function without callback is deprecated.

The only changes I've made are updating to 0.4.2 and changing the chromedriver.exe to 2.33
I think the driver is installed correctly since this code is working fine

`var AxeBuilder = require('axe-webdriverjs');
var WebDriver = require('selenium-webdriver');

var driver = new WebDriver.Builder()
  .forBrowser('chrome')
  .build();
driver.manage().timeouts().setScriptTimeout(5000); 
driver
  .get('http://example.org/')
  .then(function () {
    AxeBuilder(driver)
      .analyze(function (results) {
        console.log(results.violations);
      });
  });
driver.quit();
`

Windows 10 64bit, Nodejs 8.9.1

edit:
The first problem is with your example website from the docs... mydomain.org doesn't exist.
The second is with example.org, probably because it doesn't have any links?

edit2:
I tried scanning a simple website 
axe-crawler canappka.pl
and I'm just getting this
https://i.imgur.com/49CwKG1.png

**Comment by jasonday** [comment] 2017-11-14 14:51
> Are you using node v6.11 or higher? That's the only other thing I can think of, if the Logger class introduced the error, then maybe my babel preset is targeting a feature your node version doesn't support?

I'm running node 8.9.1. I will test the latest version with my current version of node and then against node 6.11.

**Comment by jasonday** [comment] 2017-11-14 16:37
With Node 8.9.1, axe-crawler 0.4.2 and removing and re-adding chromedriver paths I'm getting the error below. However, if I use the `--output` functionality, it does spit out a fully formed report. 

```
PS C:\Users\spjbd> axe-crawler google.com --depth 0 --output test-report
[1114/113249.441:ERROR:devtools_http_handler.cc(786)]
DevTools listening on 127.0.0.1:12468

[1114/113251.917:ERROR:devtools_http_handler.cc(786)]
DevTools listening on 127.0.0.1:12409

[1114/113254.210:ERROR:devtools_http_handler.cc(786)]
DevTools listening on 127.0.0.1:12858

[1114/113256.586:ERROR:devtools_http_handler.cc(786)]
DevTools listening on 127.0.0.1:12974

(node:1076) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:1076) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
PS C:\Users\spjbd>
```

**Comment by tjscollins** [comment] 2017-11-14 22:07
@jasonday 
Looks like there's a combination of issues caused by my having not upgraded to or tested on Node 8 yet, and some issues that look specific to the Windows version of Selenium which seems to be forwarding the browser console to the windows command console.

I fixed the deprecation warnings already on the dev branch, those will be included in v0.4.3.

I'll set up a Windows10 VM today and take a look at it.

**Comment by tjscollins** [comment] 2017-11-14 22:08
@AgnieszkaBorucka:
> edit:
> The first problem is with your example website from the docs... mydomain.org doesn't exist.
> The second is with example.org, probably because it doesn't have any links?

That's because those are fake domains you should replace with the domain you want to test.  They're just examples.

>edit2:
>I tried scanning a simple website
>axe-crawler canappka.pl
>and I'm just getting this: 
> https://i.imgur.com/49CwKG1.png

That looks like the Windows version of Selenium or Chrome is logging the browser console to the node console.  Assuming you see the same message in the browser console when viewing that site, it's not caused by axe-crawler.

Are you getting a reports.json and reports.html created when you run it against that domain?

**Comment by tjscollins** [comment] 2017-11-14 22:31
After testing in Windows, it looks like the log statements such as

> [1114/113249.441:ERROR:devtools_http_handler.cc(786)]
> DevTools listening on 127.0.0.1:12468

are indeed being passed from Chrome to node via Selenium.  Not much I can do about those as those are events happening in the browser when your target site is loaded, though I will look into suppressing the messages if the log level is configured below 'debug.'

**Comment by tjscollins** [comment] 2017-11-15 00:04
Discovered the bug that was directly causing the

> (node:15836) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): TypeError: Cannot read property 'verbose' of undefined

message.  Turns out that if you pass a class method directly as a callback like `Promise(() => {}).catch(logger.error)`, the method becomes disconnected from the logger object and it's 'this' value is undefined.  Switching to `Promise(() => {}).catch(err => logger.error(err))` solves this and the error gets logged correctly now.  Will be fixed in v0.4.3.

**Comment by tjscollins** [comment] 2017-11-15 00:50
I've published v0.4.3, after testing on Node 8 on Windows.  This fixes the DeprecationWarnings that I was able to reproduce, and fixes the UnhandledPromises that I was able to reproduce.

It does not suppress the logging from Selenium.  I'm working on that, but Selenium's JS documentation isn't super clear to me, so that may take a while (I'd happily accept a pull request if anyone else manages it, since it only happens on Windows).

@AgnieszkaBorucka I tested v0.4.3 against your domain in Windows w/ Node 8.9.1 and it seems to work now if you ignore the browser log showing up in the console (as I said, I'll work on that, but I'm not sure how long it will take).  I get both reports files out now as well.  Please let me know if it works for you.

@jasonday Running `axe-crawler google.com --depth 0` works in Windows w/ Node 8.9.1 (again, if you ignore the browser logging).  Let me know if it's working for you.

**Comment by jasonday** [comment] 2017-11-15 01:34
I'll test tonight and report back. Also, I don't mind the browser logging, as I've also experienced it using axe-webdriver. 

Edit: It's now working in Windows with Node 8.9.1 - Thanks for the quick turnaround!

**Closed as completed** 2017-11-15 02:26 UTC

**Comment by jasonday** [comment] 2017-11-17 13:15
@tjscollins - Ran into an issue with the browser logging. Running a crawl on our site with `--depth 1` (roughly 150 urls), the crawler exited with a memory issue. Our site (being larger) produces lengthy log statements, and I'm wondering if that caused it to overload.

**Comment by tjscollins** [comment] 2017-11-17 21:10
@jasonday I doubt it's the browser log.  More likely the problem is storing all the test results in one big object.  At 150 urls with 4 viewPorts that object is probably going to be 100+ MB.

The solution is probably to switch from storing all results in memory and writing them all at once when finished at the end to using a stream approach writing them to disk as they finish and not storing them all in RAM for the duration, but that'll take some work to implement.  Can you open a new issue for this?

**Comment by jasonday** [comment] 2017-11-17 23:21
Can do. Thanks!

Also, that's what the-a11y-machine does. It writes each 'page' to a file in a dynamic directory, and then compiles them all into a result.
